
services:
  postgres:
    image: postgres:16
    container_name: school_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user123
      POSTGRES_DB: school_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  db_data:
